name: sixam_mart_store
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  path_provider: ^2.1.5
  shimmer_animation: ^2.2.2
  image_picker: ^1.2.0
  http: ^1.5.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.2
  vibration: ^3.1.4
  audioplayers: ^6.5.1
  flutter_switch: ^0.3.2
  flutter_typeahead: ^5.2.0
  phone_numbers_parser: ^9.0.15
  country_code_picker: ^3.4.1
  flutter_widget_from_html_core: ^0.17.0
  photo_view: ^0.15.0
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  cached_network_image: ^3.4.1
  print_bluetooth_thermal: ^1.1.6
  flutter_esc_pos_utils: ^1.0.1
  screenshot: ^3.0.0
  http_parser: ^4.1.2
  path: ^1.9.1
  intl: ^0.20.2
  image: ^4.5.4
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  just_the_tooltip: ^0.0.12
  flutter_inappwebview: ^6.1.5
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.1
  card_swiper: ^3.0.1
  file_picker: ^10.3.3
  video_player: ^2.10.0
  chewie: ^1.13.0
  fluttertoast: ^9.0.0
  flutter_foreground_task: ^9.1.0
  flutter_image_compress: ^2.4.0

  #Rental Module
  dropdown_button2: ^2.3.9
  lottie: ^3.3.2
  syncfusion_flutter_datepicker: ^31.1.23

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/taxi_image/
    - assets/language/
    - assets/notification.mp3
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900